### ISSUE TITLE
Bug - The 'X' icon is getting cut off

### ISSUE THREAD

**Issue by Guyfrom303** [ftakj/fta_bug_reports#4]
in the Log in and Sign up window this icon is getting cut off. 

is this an "x" icon to close the window?, just clicking out side of the log in window closes the module.

![image](https://user-images.githubusercontent.com/54698438/64912514-cb6ca900-d6ed-11e9-9eab-cb610752bc90.png)

**Comment by ftakj** [comment]
Resolved
