### ISSUE TITLE
Suggestion - Try again button does not do anything

### ISSUE THREAD

**Issue by Guyfrom303** [ftakj/fta_bug_reports#6]
When creating an account the 'Try again' button does not do anything. 
 if pressing it send the user a second email then maybe rename the button to 'Resend email' or something like that. 

![image](https://user-images.githubusercontent.com/54698438/64912562-682f4680-d6ee-11e9-97ce-a7e884a89b87.png)

**Comment by ftakj** [comment]
Resolved
